# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CUSTOM_AXIS_IP_RM/CUSTOM_AXIS_IP_RM.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0/CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_dma_0_0/CUSTOM_AXIS_IP_RM_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_axi_dma_0_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_axi_dma_0_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_xbar_0/CUSTOM_AXIS_IP_RM_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_xbar_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_xbar_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_ps8_0_axi_periph_0/CUSTOM_AXIS_IP_RM_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_ps8_0_axi_periph_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0/CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/CUSTOM_AXIS_IP_RM_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_axi_smc_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_axi_smc_0} -quiet] -quiet

# Block Designs: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/bd_f701.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_0/bd_f701_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_1/bd_f701_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_2/bd_f701_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_3/bd_f701_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_4/bd_f701_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_5/bd_f701_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_6/bd_f701_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_7/bd_f701_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_8/bd_f701_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_9/bd_f701_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_10/bd_f701_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_11/bd_f701_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_12/bd_f701_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_13/bd_f701_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_14/bd_f701_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_15/bd_f701_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_16/bd_f701_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_17/bd_f701_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_18/bd_f701_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_19/bd_f701_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_20/bd_f701_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_21/bd_f701_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_22/bd_f701_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_23/bd_f701_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_24/bd_f701_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_25/bd_f701_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_26/bd_f701_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_AXIS_FIFO_CUSTOM_RM_0_0/CUSTOM_AXIS_IP_RM_AXIS_FIFO_CUSTOM_RM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_AXIS_FIFO_CUSTOM_RM_0_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_AXIS_FIFO_CUSTOM_RM_0_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_ds_0/CUSTOM_AXIS_IP_RM_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_pc_0/CUSTOM_AXIS_IP_RM_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_auto_pc_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_auto_pc_0} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_ds_1/CUSTOM_AXIS_IP_RM_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_1 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_1} -quiet] -quiet

# IP: bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_pc_1/CUSTOM_AXIS_IP_RM_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_auto_pc_1 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_auto_pc_1} -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0/CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0/CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_dma_0_0/CUSTOM_AXIS_IP_RM_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_axi_dma_0_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_dma_0_0/CUSTOM_AXIS_IP_RM_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_axi_dma_0_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0/CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0/CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_rst_ps8_0_99M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_1/bd_f701_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_1/bd_f701_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_2/bd_f701_arsw_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_3/bd_f701_rsw_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_4/bd_f701_awsw_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_5/bd_f701_wsw_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_6/bd_f701_bsw_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_10/bd_f701_s00a2s_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_11/bd_f701_sarn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_11/bd_f701_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_12/bd_f701_srn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_12/bd_f701_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_16/bd_f701_s01a2s_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_17/bd_f701_sawn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_17/bd_f701_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_18/bd_f701_swn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_18/bd_f701_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_19/bd_f701_sbn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_19/bd_f701_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_20/bd_f701_m00s2a_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_21/bd_f701_m00arn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_21/bd_f701_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_22/bd_f701_m00rn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_22/bd_f701_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_23/bd_f701_m00awn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_23/bd_f701_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_24/bd_f701_m00wn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_24/bd_f701_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_25/bd_f701_m00bn_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/bd_0/ip/ip_25/bd_f701_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_axi_smc_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_ds_0/CUSTOM_AXIS_IP_RM_auto_ds_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_0 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_ds_0/CUSTOM_AXIS_IP_RM_auto_ds_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_pc_0/CUSTOM_AXIS_IP_RM_auto_pc_0_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_ds_1/CUSTOM_AXIS_IP_RM_auto_ds_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_1 || ORIG_REF_NAME==CUSTOM_AXIS_IP_RM_auto_ds_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_ds_1/CUSTOM_AXIS_IP_RM_auto_ds_1_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/ip/CUSTOM_AXIS_IP_RM_auto_pc_1/CUSTOM_AXIS_IP_RM_auto_pc_1_ooc.xdc

# XDC: c:/Users/hp/Folder_Tugas_VIVADO/KRIA_CUSTOM_AXIS_IP_RM/KRIA_CUSTOM_AXIS_IP_RM.gen/sources_1/bd/CUSTOM_AXIS_IP_RM/CUSTOM_AXIS_IP_RM_ooc.xdc
